version: '3'

services:

  boat-postgres:
    image: "postgres:9.6-alpine"
    container_name: boat-postgres
    volumes:
      - boat-data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    expose:
      - "5433"
    environment:
      - POSTGRES_DB=boat
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    networks:
      - my_network

  boat-back:
    build: ./boat-back
    container_name: boat-back
    environment:
      - DB_SERVER=boat-postgres
      - POSTGRES_DB=boat
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    ports:
      - 8081:8080
    links:
      - boat-postgres
    networks:
      - my_network

  boat-front:
    build: ./boat-front
    container_name: boat-front
    ports:
      - 4200:4200
    links:
      - boat-back

volumes:
  boat-data:
  
networks:
  my_network:
    driver: bridge